version: 2.1
orbs:
  node: circleci/node@2.1.1

jobs:
  test:
    executor:
      name: node/default
      tag: "12.16.3"
    steps:
      - checkout
      - node/install-packages
      - node/run_tests_with_npm
      - store_artifacts:
          path: ~/project/coverage
          prefix: coverage

workflows:
  test:
    jobs:
      - node/test